[package]
name = "pantheon"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
hermes-log = { path = "../modules/hermes-log/" }
pantheon-core = { path = "../modules/pantheon-core/" }
argus-io = { path = "../modules/argus-io/" }
winit = "0.30.12"
