[package]
name = "pantheon-io"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
pantheon-log = { path = "../pantheon-log/" }
pantheon-core = { path = "../pantheon-core/" }
pantheon-types = { path = "../pantheon-types/" }
winit = "0.30.12"
