[package]
name = "argus-io"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
hermes-log = { path = "../hermes-log/" }
pantheon-core = { path = "../pantheon-core/" }
winit = "0.30.12"
